# Generated by Django 3.2.16 on 2023-01-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dayarrive',
            fields=[
                ('username', models.CharField(blank=True, db_collation='gbk_chinese_ci', max_length=20, null=True, verbose_name='用户姓名')),
                ('plantype', models.CharField(blank=True, db_collation='gbk_chinese_ci', max_length=20, null=True, verbose_name='预订类型')),
                ('roomid', models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name='房间号')),
                ('leavetime', models.DateField(blank=True, null=True, verbose_name='离开时间')),
            ],
            options={
                'verbose_name': '每日到达报表',
                'verbose_name_plural': '每日到达报表',
                'db_table': 'dayarrive',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Daylive',
            fields=[
                ('roomid', models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name='房间号')),
                ('name', models.CharField(blank=True, db_collation='gbk_chinese_ci', max_length=20, null=True, verbose_name='用户姓名')),
                ('leavetime', models.DateField(blank=True, null=True, verbose_name='离开时间')),
            ],
            options={
                'verbose_name': '每日入住报表',
                'verbose_name_plural': '每日入住报表',
                'db_table': 'daylive',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Livenotes',
            fields=[
                ('bid', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateField(blank=True, null=True)),
                ('yufujin', models.IntegerField(blank=True, null=True)),
                ('tiqian60', models.IntegerField(blank=True, null=True)),
                ('changgui', models.IntegerField(blank=True, null=True)),
                ('zong', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '预计入住报表',
                'verbose_name_plural': '预计入住报表',
                'db_table': 'livenotes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Moneynotes',
            fields=[
                ('bid', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateField(blank=True, null=True)),
                ('income', models.DecimalField(blank=True, db_column='income', decimal_places=4, max_digits=25, null=True)),
            ],
            options={
                'verbose_name': '预计房间收入报表',
                'verbose_name_plural': '预计房间收入报表',
                'db_table': 'moneynotes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('now_field', models.DateTimeField(db_column='now_field')),
                ('usercredit', models.CharField(blank=True, db_collation='gbk_chinese_ci', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_collation='gbk_chinese_ci', max_length=20, null=True)),
                ('roomid', models.IntegerField(blank=True, null=True)),
                ('arrivetime', models.DateField(blank=True, null=True)),
                ('leavetime', models.DateField(blank=True, null=True)),
                ('datediffer', models.BigIntegerField(blank=True, db_column='datediffer', null=True)),
                ('paytime', models.DateTimeField(blank=True, null=True)),
                ('money', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': '票据',
                'verbose_name_plural': '票据',
                'db_table': 'notes',
                'managed': False,
            },
        ),
    ]
