# Generated by Django 3.2.16 on 2023-01-02 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateField(blank=True, null=True, verbose_name='时间')),
                ('money', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='价格')),
            ],
            options={
                'verbose_name': '房间价格信息',
                'verbose_name_plural': '房间价格信息',
                'db_table': 'base',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('mail', models.CharField(blank=True, max_length=30, null=True)),
                ('mtime', models.DateField(blank=True, null=True)),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': '邮箱',
                'verbose_name_plural': '邮箱',
                'db_table': 'mailbox',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('plantype', models.CharField(blank=True, choices=[('提前60天预订', '提前60天预订'), ('常规预订', '常规预订'), ('预付金预订', '预付金预订')], max_length=20, null=True, verbose_name='预约类型')),
                ('plantime', models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 3, 1, 18, 22, 722747), null=True, verbose_name='预约时间')),
                ('arrivetime', models.DateField(blank=True, null=True, verbose_name='到达时间')),
                ('leavetime', models.DateField(blank=True, null=True, verbose_name='离开时间')),
                ('paytime', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
            ],
            options={
                'verbose_name': '预订信息',
                'verbose_name_plural': '预订信息',
                'db_table': 'plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('rid', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='房间ID')),
                ('state', models.CharField(choices=[('yes', '已住'), ('no', '空房')], max_length=3, verbose_name='房间状态')),
            ],
            options={
                'verbose_name': '房间信息',
                'verbose_name_plural': '房间信息',
                'db_table': 'room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('tmoney', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tjudge', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name': '罚单',
                'verbose_name_plural': '罚单',
                'db_table': 'ticket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('creditcard', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='信用卡号')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='姓名')),
                ('password', models.CharField(blank=True, max_length=20, null=True, verbose_name='密码')),
                ('money', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='待付金额')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('wid', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='姓名')),
                ('password', models.CharField(blank=True, max_length=20, null=True, verbose_name='密码')),
                ('identify', models.CharField(blank=True, choices=[('雇员', '雇员'), ('管理', '管理')], max_length=2, null=True, verbose_name='职位')),
            ],
            options={
                'verbose_name': '工作人员信息',
                'verbose_name_plural': '工作人员信息',
                'db_table': 'worker',
                'managed': False,
            },
        ),
    ]
